version: '3'

networks:
  location-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=172.18.0.2
      - DB_USER=locuser
      - DB_PASS=root
      - DB_NAME=locationdb
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - location-network
  db:
    image: postgres:13.8
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: locuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: locationdb
    restart: on-failure
    networks:
      - location-network